name: Deploy Website Main

on:
  Push:
    branches:
     - Main

jobs:
  Deploy:
    runs-on: ubuntun-Latest

    steps:
     - name: Deploy Website Main To Server Via SSH
       uses: appleboy/ssh-action@v1.0.3
       with:
          host: ${{secrest.IP_SERVER}}
          username: ${{secrets.USER_SERVER}}
          key: ${{secrets.PRIVATE_KEY_SERVER}}
          port: 777
          script: |
            cd /var/www/videouas
            git fetch origin
            git reset --hard origin/Main
            sudo systemctl restart nginx

